# ===============================
# APPLICATION
# ===============================
spring.application.name=trading
server.port=${PORT:8080}

# ===============================
# DATABASE (MySQL)
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:trade1}
spring.datasource.username=${DB_USERNAME:---}
spring.datasource.password=${DB_PASSWORD:------}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# EMAIL CONFIG (GMAIL SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=
spring.mail.username=shirishkanoje9@gmail.com
spring.mail.password=

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# PAYMENT KEYS
# ===============================
stripe.api.key=your_stripe_secret_key
razorpay.api.key=
razorpay.api.secret=
